language: c
install:
- sudo add-apt-repository --yes ppa:duggan/bats
- sudo apt-get update
- sudo apt-get install --yes bats
script: make check
sudo: required
services:
- docker
before_deploy:
  - export ARCHIVE_NAME=autouseradd-$TRAVIS_TAG-amd64
  - sudo make install DESTDIR="$ARCHIVE_NAME"
  - tar czf "$ARCHIVE_NAME.tar.gz" "$ARCHIVE_NAME"
deploy:
  provider: releases
  api_key:
    secure: IWVKiR4wTPHAIo4s+qGv3Q5aGWO+QM4weCAxMUxrmn8wl2nghIJkmL6mnFFHGAWigvqzPeFmmEbi153dlcj5+sqTz5ibhsDWrYtwT/FAqrz3Dj1DwLxh+9NnvSrzRfnjNqyeEWk6zEtf+zPKhH2wgR4tY2PO/X44hU6SbgXmfJpeiRO/mg/wcZa4rUXWUJJh3ac6du8RusU6cNoLeHrN5/XPVfuKQI14wikoZQBukPj76/sfntuDO1/iDgysuahzrYzAagBCkHO8bHDbDcP54VZNdRo1bRL22BtQonfVANK6WKisop1yx95KHo8aN+q9IXKrJBXIQlqJX5YcORqLvibD2FTYoYC+4KENHB9iUH/1h4LA/n+vXrUDsTcGEDkEB/mm2oF3fN6LtbsGbDuaxwX0Lhs9Ase6MYtwa/EgvNgOVviG0fHX1/CrCE7HjRVwG7O5Xc6saJGjoAIQsPtgJmzIFuPM+N9jh8ztt7YD87XBI371vHIXoVEsU7531NjvSUVXH4O/qmex6tV1to7cnHdrYdxoGPMdVfCQsoHZno028sAoHkLFS4uUbUBl2tA9Bv+u/Td8EK5gpQHI/zP3pRpqkuv/GFuN2TnC8LCr0zuorNmEzTNKcf7HpqkatrFvqB+VNKCmili8RW4df/TKdsYjYHBbnOIoD37gLnu6U54=
  skip_cleanup: true
  file: $ARCHIVE_NAME.tar.gz
  body: See the [CHANGELOG](/CHANGELOG.md) for release notes.
  on:
    repo: benesch/autouseradd
    tags: true
