.TH AUTOUSERADD 1 11/07/2017 "Autouseradd 1.1.0" "Autouseradd Manual"
.
.SH "NAME"
autouseradd \- container entrypoint for dynamic user IDs
.
.SH "SYNOPSIS"
\fBautouseradd\fR [\-u \fIname\fR] [\-g \fIname\fR] [\-s \fIpath\fR] [\fIcommand\fR [\fIargs\fR...]]
.
.SH "DESCRIPTION"
\fBautouseradd\fR adds a user and a group named after that user to the system,
then invokes \fIcommand\fR with the specified \fIargs\fR.
If \fIcommand\fR is omitted, the user's login shell is invoked instead.
The real user ID and the real group ID of the process are used as the user ID
and group ID for the created user and group, respectively.
\fBautouseradd\fR will fail if a user with the same name or ID or a group with
the same name or ID already exists.
.PP
The following options are available:
.TP 4
\fB\-u\fR \fIname\fR, \fB\-\-user\fR=\fIname\fR
Use \fIname\fR as the username for the created user. If this option is not
specified, the username defaults to \fIauto\fR.
.TP 4
\fB\-g\fR \fIname\fR, \fB\-\-group\fR=\fIname\fR
Use \fIname\fR as the username for the created group. If this option is not
specified, the group name defaults to the user name.
.TP 4
\fB\-s\fR \fIpath\fR, \fB\-\-shell\fR=\fIpath\fR
Set the user's login shell to \fIpath\fR. If this option is not specified, the
shell defaults to \fB/bin/bash\fR.
.TP 4
\fB\-M\fR, \fB\-\-no-create-home\fR
Don't attempt to create a home directory for the user.
.
.SH "EXIT STATUS"
\fBautouseradd\fR exits with a value of 1 if an error occurs, otherwise it exits
with the exit status of \fIcommand\fR.
.
.SH "AUTHORS"
\fBautouseradd\fR was written by Nikhil Benesch <\fBnikhil.benesch@gmail.com\fR>.
